export const spacesData = [
  {
    id: 1,
    categories: ["Retreat", "Wellness"],
    image: "/spaces/rido2.png",
    date: "June 10, 2021",
    name: "Rido Platform",
    location: "Cross-Device Web App",
    clientImage: "/spaces/client-1.jpeg",
    clientName: "Marina Li",
    route: "/rido",
  },
  {
    id: 2,
    categories: ["Home", "Cultural", "Residential"],
    image: "/spaces/ecomstore.png",
    date: "May 15, 2021",
    name: "Ecomstore",
    location: "Fullstack Ecommerce ",
    clientImage: "/spaces/client-2.jpeg",
    clientName: "Alex Chen",
    route: "/ecomstore",
  },
  {
    id: 3,
    categories: ["Home", "Gallery"],
    image: "/spaces/eca.png",
    date: "April 22, 2021",
    name: "ECA Nepal",
    location: "Social Collaboration",
    clientImage: "/spaces/client-3.jpeg",
    clientName: "Sophia Rodriguez",
    route: "/eca-nepal",
  },
  {
    id: 4,
    categories: ["Gallery", "Cultural"],
    image: "/spaces/admin.png",
    date: "March 8, 2021",
    name: "Fullstack Admin Dashboard",
    location: "Internal Tooling",
    clientImage: "/spaces/client-4.jpeg",
    clientName: "David Kim",
    route: "/admin-dashboard",
  },
  {
    id: 5,
    categories: ["Home", "Retreat"],
    image: "/spaces/flower.png",
    date: "February 14, 2021",
    name: "Flower and Saints Clone",
    location: "Luxury Retail",
    clientImage: "/spaces/client-5.jpeg",
    clientName: "Emma Wilson",
    route: "/flower&saints",
  },
  {
    id: 6,
    categories: ["Cultural", "Home"],
    image: "/spaces/searchengine.png",
    date: "January 30, 2021",
    name: "Search Engine",
    location: "Information Access",
    clientImage: "/spaces/client-6.jpeg",
    clientName: "Aiko Tanaka",
    route: "/search-engine",

  },
  {
    id: 7,
    categories: ["Wellness", "Retreat", "Gallery"],
    image: "/spaces/dbrand.png",
    date: "December 12, 2020",
    name: "Dbrand Clone",
    location: "GSAP Animation",
    clientImage: "/spaces/client-7.jpeg",
    clientName: "Omar Rahman",
    route: "/dbrand",
  },
];
